import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Montserrat } from 'next/font/google';

const montserrat_init = Montserrat({
  subsets:['latin'],
  weight:['400'],
  variable: '--font-Montserrat'
});



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body  className={`${geistSans.variable} ${montserrat_init.variable} ${geistMono.variable} antialiased`} >
      <div className="main  relative md:flex w-[99vw]  h-[85vh] md:h-[99vh]">
        

      <Sidebar/>
        {children}
        </div>
      </body>
    </html>
  );
}
